# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: REVAN-GA <revan-ga@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/05/08 18:29:09 by REVAN-GA          #+#    #+#              #
#    Updated: 2025/05/08 18:54:14 by REVAN-GA         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		= libftprintf.a

CC		= gcc
CFLAGS		= -Wall -Werror -Wextra
AR		= ar
RM		= rm -rf

SRC		= ft_printf ft_putchar ft_putstr ft_hexadecimal_uppercase ft_hexadecimal_lowercase ft_putadress ft_putunbr ft_putnbr
SRCS		=

OBJ_DIR		= obj
OBJS		=

LIBFT_PATH	=
LIBFT		=

$(OBJ_DIR)/.o:	%.c

all:		$(NAME)

$(NAME):	$()
